# Generated by Django 4.0.2 on 2022-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='New', max_length=30),
        ),
    ]
