# Generated by Django 4.0.2 on 2022-03-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rename_organization_agent_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='userprofile',
            new_name='organization',
        ),
    ]
